Works much better now

diff --git a/ass1/stats b/ass1/stats
--- a/ass1/stats
+++ b/ass1/stats
@@ -11,20 +11,23 @@ EXIT_ROARING_SUCCESS=0
 # Print usage information to stderr. Obviously the 1>&2 wackadoo redirects
 # stdout to stderr.
 # Don't actually exit failure, leave that to the caller.
-# Use single quotes to make it clear that all of the brackets and braces won't
-# suffer  interpolation.
 usage () {
-	echo 'Usage: stats {-rows|-cols} [file]' 1>&2
+	echo "$0 {-rows|-cols} [file]" 1>&2
 }
+
+# $# is the number of argument the script received.
+if [[ $# > 2 ]]; then
+	usage
+	exit $EXIT_EPIC_FAIL
+fi
 
 # If a file was specified and the file is not readable or there are too many
 # arguments print usage and exit.
 # The -z flag checks whether the $2 variable is set.
 # The -r flag checks whether a file exists and is readable.
 # ! is 'not`, like you expect.
-# $# is the number of argument the script received.
-if [[ ! -z $2 && ! -r $2  || $# > 2 ]]; then
-	echo "The file $2 couldn't be read." 1>&2
+if [[ ! -z $2 && ! -r $2 ]]; then
+	echo "$0: Cannot read $2" 1>&2
 	exit $EXIT_EPIC_FAIL
 fi
 
@@ -35,7 +38,7 @@ fi
 # If the first argument begins with -r
 if [[ $1 =~ ^-r ]]; then
 	# FIXME: The rounding for the averages is broken!
-	echo Average Median
+	printf "Average\tMedian\n"
 	# Way down at the end, ${2:-/dev/stdin} means use $2 or /dev/stdin if $2 is
 	# not defined. This is being redirected into the while loops which reads
 	# each line.
@@ -46,7 +49,7 @@ if [[ $1 =~ ^-r ]]; then
 		# output needs to be translated with tr. The newlines are translated
 		# into spaces because bash expects the input of a bash array to be
 		# space deliminated (by default).
-		sorted_line=$(echo $line | expand | tr ' ' '\n' | sed '/^$/d' | sort | tr '\n' ' ')
+		sorted_line=$(echo "$line" | expand | tr ' ' '\n' | sed '/^$/d' | sort -n | tr '\n' ' ')
 		# Create an array from the space deliminated line
 		line_array=($sorted_line)
 		# Use sed to transform this line so that each element is separated by
@@ -64,7 +67,7 @@ if [[ $1 =~ ^-r ]]; then
 		# The average is the sum of the elements divided by the number of
 		# elements
 		average=$(expr \( $line_as_sum + $numerator_correction \) / $line_length)
-		#echo "Average $average"
+		#echo: "Average $average"
 		#python -c "print 'py', ($line_as_sum)/$line_length"
 		#echo "median $median"
 		#python -c "l='$line'.split('\t'); mid=len(l)/2; print 'py', l[mid]"
@@ -102,10 +105,7 @@ elif [[ $1 =~ ^-c ]]; then
 	# passed emptiness.
 	if [[ $first_line_length == 0 ]]
 	then
-		echo Averages:
-		printf "\n"
-		echo Means:
-		printf "\n"
+		exit $EXIT_ROARING_SUCCESS
 	fi
 
 	# Iterate over the inclusive range from 1 to the length of the first line.
@@ -114,7 +114,7 @@ elif [[ $1 =~ ^-c ]]; then
 	do
 		# cut each column and sort it. Translate it into a newline delimited
 		# array for use by bash and expr.
-		data=$(printf "%s\n" "$file" | cut -f $index | sort | tr '\n' ' ')
+		data=$(printf "%s\n" "$file" | cut -f $index | sort -n | tr '\n' ' ')
 		# Transform the data into an array.
 		data_as_arr=($data)
 		# Find the mid point for the median.
@@ -134,7 +134,7 @@ elif [[ $1 =~ ^-c ]]; then
 	echo Averages:
 	printf "%s\t" ${averages[@]}
 	printf "\n"
-	echo Means:
+	echo Medians:
 	printf "%s\t" ${means[@]}
 	printf "\n"
 # Otherwize the user screwed up and should be given a lecture about usage.
